[versions]
aliucord = "2.6.0"
aliuhook = "1.1.4"
aliucord-gradle = "2.3.0"
android = "8.13.0"
discord = "126021"
kotlin = "2.2.20"
#noinspection GradleDependency
kotlin-stdlib = "1.5.21"
ktlint = "1.7.1"
ktlint-plugin = "13.1.0"
shadow = "8.3.8"

[libraries]
aliucord = { module = "com.aliucord:Aliucord", version.ref = "aliucord" }
aliuhook = { module = "com.aliucord:Aliuhook", version.ref = "aliuhook" }
discord = { module = "com.discord:discord", version.ref = "discord" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }

[plugins]
aliucord-plugin = { id = "com.aliucord.plugin", version.ref = "aliucord-gradle" }
android-library = { id = "com.android.library", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
